In [1]:
import numpy as np

## Data Types & Attributes

In [3]:
# NumPy's main Data Types is ndarray
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [6]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6], 
                [7, 8, 9]],
               
              [[10, 11, 12], 
               [13, 14, 15], 
               [15, 16, 17]]
              ])

In [10]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [15, 16, 17]]])

In [12]:
a1.shape

(4,)

In [19]:
a2.shape

(2, 3)

In [20]:
a3.shape

(2, 3, 3)

In [24]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [25]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [26]:
a1.size, a2.size, a3.size

(4, 6, 18)

In [27]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [29]:
# Create a dataframe from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## Creating array

In [30]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [31]:
sample_array.dtype

dtype('int32')

In [32]:
ones = np.ones((2, 3, 4))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [33]:
ones.dtype

dtype('float64')

In [34]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
range_array = np.arange(0, 20, 2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[7, 1, 2, 5, 7],
       [3, 3, 6, 2, 1],
       [0, 9, 5, 1, 8]])

In [42]:
random_array.shape

(3, 5)

In [44]:
random_array.size

15

In [47]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.29867093, 0.61993458, 0.84718862],
       [0.03472537, 0.33174962, 0.26648566],
       [0.44361226, 0.67758347, 0.0032385 ],
       [0.18819392, 0.94513213, 0.97123147],
       [0.01489493, 0.64322502, 0.38786891]])

In [48]:
random_array_3 = np.random.rand(3, 5)
random_array_3

array([[0.01236664, 0.7414899 , 0.33413762, 0.9133442 , 0.45585364],
       [0.48274604, 0.03801588, 0.82106465, 0.23122015, 0.05629498],
       [0.17476587, 0.09086777, 0.37142002, 0.89594556, 0.44128034]])

In [65]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [75]:
np.random.seed(7)
random_array_5 = np.random.random((5,2))
random_array_5

array([[0.07630829, 0.77991879],
       [0.43840923, 0.72346518],
       [0.97798951, 0.53849587],
       [0.50112046, 0.07205113],
       [0.26843898, 0.4998825 ]])

## Viewing Arrays and Matrices

In [77]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [15, 16, 17]]])

In [86]:
a3[1][2][2] 

17

In [82]:
 a3[:1, :2, :2]

array([[[1, 2],
        [4, 5]]])

In [83]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[4, 0, 7, 0, 7],
         [6, 3, 5, 8, 8],
         [7, 5, 0, 0, 2],
         [8, 9, 6, 4, 9]],

        [[7, 3, 3, 8, 3],
         [0, 1, 0, 0, 6],
         [7, 7, 9, 3, 0],
         [7, 7, 7, 0, 5]],

        [[4, 3, 1, 3, 1],
         [3, 4, 3, 1, 9],
         [5, 9, 1, 2, 3],
         [2, 2, 5, 7, 3]]],


       [[[0, 9, 9, 3, 4],
         [5, 3, 0, 4, 8],
         [6, 7, 2, 7, 3],
         [8, 6, 6, 5, 6]],

        [[5, 7, 1, 5, 4],
         [4, 9, 9, 0, 6],
         [2, 6, 8, 2, 4],
         [1, 6, 1, 5, 1]],

        [[6, 9, 8, 6, 5],
         [9, 7, 5, 4, 9],
         [6, 8, 1, 5, 5],
         [8, 3, 7, 7, 9]]]])

In [84]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [89]:
 # Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[4, 0, 7, 0],
         [6, 3, 5, 8],
         [7, 5, 0, 0],
         [8, 9, 6, 4]],

        [[7, 3, 3, 8],
         [0, 1, 0, 0],
         [7, 7, 9, 3],
         [7, 7, 7, 0]],

        [[4, 3, 1, 3],
         [3, 4, 3, 1],
         [5, 9, 1, 2],
         [2, 2, 5, 7]]],


       [[[0, 9, 9, 3],
         [5, 3, 0, 4],
         [6, 7, 2, 7],
         [8, 6, 6, 5]],

        [[5, 7, 1, 5],
         [4, 9, 9, 0],
         [2, 6, 8, 2],
         [1, 6, 1, 5]],

        [[6, 9, 8, 6],
         [9, 7, 5, 4],
         [6, 8, 1, 5],
         [8, 3, 7, 7]]]])

## Manipulating Arrays

### Arithmetic 

In [103]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [104]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [106]:
a1 + ones

array([2., 3., 4.])

In [107]:
a1 - ones

array([0., 1., 2.])

In [108]:
a1 * ones

array([1., 2., 3.])

In [109]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [114]:
a3[:2, :3]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [15, 16, 17]]])

In [120]:
# how to reshape numpy array a2 * a3

In [121]:
a1 / ones

array([1., 2., 3.])

In [122]:
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]], dtype=int32)

In [123]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [125]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [126]:
np.add(a1, ones)

array([2., 3., 4.])

In [127]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [128]:
a1 / 2

array([0.5, 1. , 1.5])

In [129]:
a2 % 2

array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [130]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [131]:
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [132]:
np.log(a2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

## Aggregation

In [133]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [134]:
sum(listy_list)

6

In [135]:
type(a1)

numpy.ndarray

In [136]:
sum(a1)

6

In [137]:
np.sum(a1)

6

In [139]:
 # Creative a massive numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [140]:
massive_array[:10]

array([0.513401  , 0.17842575, 0.39200156, 0.93959276, 0.21291858,
       0.81329627, 0.40364858, 0.58672092, 0.18599889, 0.81232251])

In [141]:
%timeit sum(massive_array) # Pythons's sum()
%timeit np.sum(massive_array) # NumPy's array

7.22 ms ± 303 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
42.3 µs ± 398 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [143]:
7220 / 42.3

170.6855791962175

In [144]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
np.mean(a2)

3.5

In [146]:
np.max(a2)

6

In [147]:
np.min(a2)

1

In [148]:
# Standard Deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.707825127659933

In [149]:
# Variance = measure of the average degree to which each number is different
# Higher Variance = wider range of numbers
# Lower Variance = lower range of numbers
np.var(a2)

2.9166666666666665

In [152]:
# Standard  Deviation = Square root of Variance
np.sqrt(np.var(a2))

1.707825127659933

In [151]:
#Video --> 10